### ISSUE TITLE
Replace Tyr with PHPMailer

### ISSUE THREAD

**Issue by slylth** [reasoncms/reasoncms#164]
Replace Tyr with a more robust [PHPMailer](https://github.com/PHPMailer/PHPMailer) library.

See [discussion](https://groups.google.com/forum/?fromgroups#!topic/reason-discussion/Qa_bShARFUA).

**Comment by mryand** [comment]
This has been replaced at Carleton. @laupow I'm assuming this will be in a Carleton pull request?

**Comment by laupow** [comment]
PHPMailer will appear in a 4.8 push of commits from Carleton (we're not quite in pull request model yet).

A slight note: Tyr still exists, as PHPMailer is more of a delivery tool. Tyr is also a heavy a templating/formatting tool, so we can't directly replace Tyr with PHPMailer. Changes specifically to Tyr can be handled in another issue. For the time being, PHPMailer will be available via Tyr and the Email class, but also as a general 3rd party lib included with Reason.
