### ISSUE TITLE
Remove heavy reliance on .htaccess files

### ISSUE THREAD

**Issue by laupow** [reasoncms/reasoncms#185]
Reason currently writes .htaccess files to disk as the primary method to resolve URLs to a Reason-maintained resource. 

For a [variety](https://httpd.apache.org/docs/current/howto/htaccess.html#when) of [reasons](https://www.nginx.com/resources/wiki/start/topics/examples/likeapache-htaccess/) this is increasingly inflexible and no longer best practice. There are performance and security considerations of such heavy usage of .htaccess files and Reason has a subtle requirement of Apache 2.2 for a web server (Apache 2.4 or nginx won't work).

We should move in a direction where all requests are funneled to a single bootstrap/index file when a resource doesn't exist on disk and depreciate/remove the url_manager functionality. The bootstrap file resolves URLs to Reason resources dynamically. This is how modern web applications are structured and we can draw on other projects/frameworks for examples. 

Much of the the logic needed to make this change already exists but is fragmented across files in different contexts. I'd recommend we proceed by incorporating an [established tool](http://laravel.com/docs/5.1/routing#basic-routing) so we can focus on the Reason-specific routing requirements as opposed to writing something from scratch.

Questions/considerations:
1) Many modern PHP framework/packages that we could include for this project require PHP >= 5.5.9. That version has been out for almost 2 years and is fairly easy to obtain on most OSes and shared hosting providers, but is a big jump for the project.

2) Do we want to provide backward compatibility for the .htaccess writing? What would that look like?

I will be working on this _eventually_ as there is a need at Carleton, but the our timeline isn't clear yet.

**Comment by mryand** [comment]
Here is a library that is narrowly focused on routing; perhaps worth looking at:

https://github.com/dannyvankooten/AltoRouter

**Comment by mryand** [comment]
Nick says that Beloit is running Apache 2.4.18 and Steve says that Luther is running Apache 2.4.7. They both say that it seems to be working fine. Matt, can you be more specific about what issues you would anticipate on Apache > 2.2?

**Comment by laupow** [comment]
There are some upgrade docs here 
https://httpd.apache.org/docs/current/upgrading.html
which list breaking changes. 

Reason uses some 2.2 syntax rules at https://github.com/carleton/reason_package/blob/master/reason_4.0/lib/core/classes/url_manager.php#L181
which may cause issues. I recall running into issues here, but not the circumstances.
