### ISSUE TITLE
Policy Module - Broken JS Include

### ISSUE THREAD

**Issue by mischler** [reasoncms/reasoncms#234]
I was looking into the Policy Module and ran across what appears to be a typo.

 **reason_package/reason_4.0/lib/core/minisite_templates/modules/policy.php, line 84**
   `$head->add_javascript('/reason_package/reason_4.0/www/js/policy_selector.js');`

The [`add_javascript` function](https://github.com/carleton/reason_package/blob/fa0b0cc49183af587a4a17ce547e5c81d0352128/reason_4.0/lib/core/classes/head_items.php) appears to expect a URL rather than a direct path for the first parameter.  However, this function is given a direct path, so the URL produced is invalid.  Looking at the function, I see there is an option to use direct path via the `$inline` parameter.

I would submit a pull request to correct this, but I'm not sure if there there is a preferred approach in regards to this function:

 **URL Path**
   `$head->add_javascript('/reason/js/policy_selector.js');`

 **Direct Path**
   `$head->add_javascript('/reason_package/reason_4.0/www/js/policy_selector.js', false, array('before'=>'','after'=>''), true);`

**Comment by mryand** [comment]
The problem with this approach is that it depends on Reason being unpacked
in a particular location on the server, which we should not assume in our
code.

This will be more robust:

$this->head_items->add_javascript(WEB_JAVASCRIPT_PATH
.'policy_selector.js');

**Comment by mischler** [comment]
https://github.com/carleton/reason_package/pull/235
