### ISSUE TITLE
Replace registration slots with an event-form linkage

### ISSUE THREAD

**Issue by mryand** [reasoncms/reasoncms#237]
Registration slots are very inflexible. We often want to ask for meal preferences, etc. and to do ticketing (where a single person reserves multiple tickets for an event), and registration slots don't allow either of these.

We envision a relationship between events and forms, allowing forms to take the place of registration slots.

**Comment by laupow** [comment]
Update - the work is done here, it'll show up in 4.8. I'm going to close this issue -- but there's another for future requests ( #200 )
