### ISSUE TITLE
Can't upload image to reasoncms

### ISSUE THREAD

**Issue by brifishjones** [reasoncms/reasoncms#259]
Error message from /var/log/apache2/reason_error.log:
PHP Fatal error:  Call to a member function get_filename() on a non-object in /var/reason_package/reason_4.0/lib/core/scripts/upload/receive.php on line 62, referer: https://reasoncms.org/reason/admin/index.php?site_id=240622&type_id=243&id=242974&rel_id=&cur_module=Editor&new_entity=1&user_id=&open=

**Comment by mryand** [comment]
This is now resolved.
